### ISSUE TITLE
special characters appear as other special characters

### ISSUE THREAD

**Issue by MareoRaft** [tylerbutler/xkcd2#9]
Something odd is going on with the special characters.  They are not the correct characters.

Example:

![screen shot 2015-12-04 at 12 59 42 pm](https://cloud.githubusercontent.com/assets/860303/11597058/1b71e9b2-9a87-11e5-8817-4b48ca45f05e.png)

Let me know if you need more info.  Thanks!

**Comment by tylerbutler** [comment]
Seems to be fixed now: <http://xkcd2.com/847/>
